### ISSUE TITLE
Inability to handle manifests with comments next to e.g. object keys

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/kube2pulumi#101]
### What happened?

Inability to handle manifests with comments next to e.g. object keys

### Example

```
    volumeMounts:
        # Unprivileged containers need to mount /proc/sys/net from the host
        # to have write access
        - mountPath: /host/proc/sys/net
          name: host-proc-sys-net
        # Unprivileged containers need to mount /proc/sys/kernel from the host
        # to have write access
```

### Output of `pulumi about`

kube2pulumi 0.0.15

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
@phillipedwards Could you please specify the error that you are currently getting?

**Comment by zbuchheit** [comment]
@mikhailshilkov 

Here is an example I used and it has example comments that result in failure. From my tests it seems like it might be upset about yaml arrays with comments. I left comments noting which ones are accepted with `This Works` and breaking ones with `Breaking Comment`. The breaking comments resulted in the same errors. Hope this is helpful

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      #This Works
      - name: nginx
        image: nginx:latest
        #This Works
        ports:
        - containerPort: 80
        args:
        - "one_value"
        - "two_value"
        #Breaking Comment
        - "three_value"
        - "four_value"
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
        env:
        - name: STRING_ARRAY
          value: "string"
        #Breaking Comment
        - name: STRING_ARRAY2
          value: "string"
```

⚠️Error Below⚠️

```
Error: Error: Invalid expression

  on pcl-3782226398.pp line 37:
  38: ]

Expected the start of an expression, but found an invalid expression token.


Usage:
  kube2pulumi all [flags]

Flags:
  -h, --help   help for all

Global Flags:
  -d, --directory string    file path for directory to convert
  -f, --file string         YAML file to convert
  -o, --outputFile string   The name of the output file to write to

unable to run program: Error: Invalid expression

  on pcl-3782226398.pp line 37:
  38: ]

Expected the start of an expression, but found an invalid expression token.
```
