### ISSUE TITLE
need to handle duplicate resource names across .yaml file in directory

### ISSUE THREAD

**Issue by sashu-shankar** [pulumi/kube2pulumi#11]
raw YAML for failing PCL (currently in separate files in same directory): 
```yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pulumi-kubernetes-operator
subjects:
  - kind: ServiceAccount
    name: pulumi-kubernetes-operator
roleRef:
  kind: Role
  name: pulumi-kubernetes-operator
  apiGroup: rbac.authorization.k8s.io

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pulumi-kubernetes-operator
```

Failing PCL for pcl2pulumi: 
```yaml
resource pulumi-kubernetes-operator "kubernetes:rbac.authorization.k8s.io/v1:RoleBinding" {
kind = "RoleBinding"
apiVersion = "rbac.authorization.k8s.io/v1"
metadata = {
name = "pulumi-kubernetes-operator"
}
subjects = [
{
kind = "ServiceAccount"
name = "pulumi-kubernetes-operator"
}
]
roleRef = {
kind = "Role"
name = "pulumi-kubernetes-operator"
apiGroup = "rbac.authorization.k8s.io"
}
}

resource pulumi-kubernetes-operator "kubernetes:core/v1:ServiceAccount" {
apiVersion = "v1"
kind = "ServiceAccount"
metadata = {
name = "pulumi-kubernetes-operator"
}
}
```

Code Segment:
```golang
	filePath := "testdata/k8sOperator/"
	result, err := yaml2pcl.ConvertDirectory(filePath)
	if err != nil {
		fmt.Println(err)
		return
	}
	//output format options are "nodejs", "python", "dotnet", "go"
	err = pcl2pulumi.Pcl2Pulumi(result, filePath, "python")

	if err != nil {
		fmt.Println(err)
	}
```

Error: `"pulumi-kubernetes-operator" already declared`
