### ISSUE TITLE
Parsing can sometimes use the wrong name/namespace values for generating the resource name.

### ISSUE THREAD

**Issue by rquitales** [pulumi/kube2pulumi#112]
### What happened?

The current logic for parsing the resource name (using the object's name and namespace) is done by iterating over every filtered `ast.MappingValueType` fields within the `.metadata` block of the yaml. This is not reliable as we could have nested `name`/`namespace` fields within an annotation or label. For example from the following test data: https://github.com/pulumi/kube2pulumi/blob/752b9834f6628adf4cba319869acea4e3873982e/testdata/OnePodArray/OnePodArray.yaml#L1C3-L1C3

If we added additional fields to the annotations as such:
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    name: fake
    namespace: fake
  namespace: foo
  name: bar
spec:
  containers:
    - name: nginx
      image: nginx:1.14-alpine
      resources:
        limits:
          memory: 20Mi
          cpu: 0.2

```

This still outputs the correct `fooBarPod` resource name. This is because the wanted `name`/`namespace` fields are below the annotations block. If we moved the annotations block around, which is still valid KRM, we actually get the wrong resource name of: `fakeFakePod`.

```yaml
# kube2pulumi generates the wrong resource name.
apiVersion: v1
kind: Pod
metadata:
  namespace: foo
  name: bar
  annotations:
    name: fake
    namespace: fake
spec:
  containers:
    - name: nginx
      image: nginx:1.14-alpine
      resources:
        limits:
          memory: 20Mi
          cpu: 0.2
```

We should use a more deterministic way of getting these fields, perhaps using the `node.GetPath()` methods to match exact yaml paths for these fields.

### Example

Looping logic: https://github.com/pulumi/kube2pulumi/blob/752b9834f6628adf4cba319869acea4e3873982e/pkg/yaml2pcl/yaml2pcl.go#L195-L206

### Output of `pulumi about`

Affects all versions of kube2pulumi.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
