### ISSUE TITLE
incorrect handling of .status field in YAML manifests: needs to be ignored

### ISSUE THREAD

**Issue by sashu-shankar** [pulumi/kube2pulumi#32]
Sample YAML: 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2020-08-04T18:50:43Z"
  generation: 1
  name: argocd-server
  namespace: default
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-08-04T18:51:31Z"
    lastUpdateTime: "2020-08-04T18:51:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-08-04T18:50:43Z"
    lastUpdateTime: "2020-08-04T18:51:31Z"
    message: ReplicaSet "argocd-server-7778cdd5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

PCL conversion parses the status field which then causes an issue when generating code. Status is an output field and needs to be ignored when parsing. kube2pulumi currently panics out with no output in the pcl2pulumi conversion
