### ISSUE TITLE
Not correctly handling properties with `:` characters?

### ISSUE THREAD

**Issue by lukehoban** [pulumi/kube2pulumi#36]
Attempting to convert this:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: pulumi-api-secret
type: Opaque
stringData:
  accessToken: "<REDACTED: PULUMI_ACCESS_TOKEN>"
---
apiVersion: v1
kind: Secret
metadata:
  name: pulumi-aws-secrets
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "<REDACTED: AWS_ACCESS_KEY_ID>"
  AWS_SECRET_ACCESS_KEY: "<REDACTED: AWS_SECRET_ACCESS_KEY>"
---
apiVersion: pulumi.com/v1alpha1
kind: Stack
metadata:
  name: s3-bucket-stack
spec:
  accessTokenSecret: pulumi-api-secret
  envSecrets:
    - pulumi-aws-secrets
  stack: joeduffy/s3-op-project/dev
  initOnCreate: true # noop if stack already exists
  projectRepo: https://github.com/joeduffy/test-s3-op-project
  commit: cc5442870f1195216d6bc340c14f8ae7d28cf3e2
  config:
    aws:region: us-east-2
```

Fails with this:

```
[31mError[0m: Missing attribute separator

  on pcl-859051780.pp line 40:
  40: config = {
  41: aws:region [1;4m=[0m "us-east-2"

Expected a newline or comma to mark the beginning of the next attribute.
```

Seems to be a problem with the key being named `aws:region` (which YAML supports just fine, but perhaps one of our conversion steps doesn't?).

Aside - it's a bit of a shame that we surface `pcl-859051780.pp` here - since it's not something the user has any control over or understanding of.
