### ISSUE TITLE
[yaml2pcl] null value generates invalid PCL

### ISSUE THREAD

**Issue by lblackstone** [pulumi/kube2pulumi#4]
The following YAML generates invalid PCL:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: pulumi-kubernetes-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
```

```
resource pulumi-kubernetes-operator "kubernetes:rbac.authorization.k8s.io/v1:Role" {
	apiVersion = "rbac.authorization.k8s.io/v1"
	kind = "Role"
	metadata = {
		creationTimestamp = name = "pulumi-kubernetes-operator"
	}
	rules = [
		{
		apiGroups = [
			""""
		]
		resources = [
			"pods"
		]
		verbs = [
			"get"
		]
		}
	]
}
```

It looks like the `null` value isn't being handled properly.
