### ISSUE TITLE
[yaml2pcl] quotes in YAML generates invalid PCL

### ISSUE THREAD

**Issue by lblackstone** [pulumi/kube2pulumi#5]
The following YAML generates invalid PCL:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pulumi-kubernetes-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
```

```
resource pulumi-kubernetes-operator "kubernetes:rbac.authorization.k8s.io/v1:Role" {
	apiVersion = "rbac.authorization.k8s.io/v1"
	kind = "Role"
	metadata = {
		name = "pulumi-kubernetes-operator"
	}
	rules = [
		{
		apiGroups = [
			""""
		]
		resources = [
			"pods"
		]
		verbs = [
			"get"
		]
		}
	]
}
```

The `""` string under `apiGroups` is incorrectly generating an extra set of `""` in the PCL. It should instead be:

```
apiGroups = [
    ""
]
```
