### ISSUE TITLE
vpc-resource-controller yaml fails to parse

### ISSUE THREAD

**Issue by gitfool** [pulumi/kube2pulumi#55]
[`vpc-resource-controller.yaml`](https://amazon-eks.s3.us-west-2.amazonaws.com/manifests/us-west-2/vpc-resource-controller/latest/vpc-resource-controller.yaml) from Amazon EKS [Windows Support](https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html):
```yml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vpc-resource-controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/status
  - pods
  - configmaps
  verbs:
  - update
  - get
  - list
  - watch
  - patch
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vpc-resource-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vpc-resource-controller
subjects:
- kind: ServiceAccount
  name: vpc-resource-controller
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vpc-resource-controller
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpc-resource-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpc-resource-controller
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: vpc-resource-controller
        tier: backend
        track: stable
    spec:
      serviceAccount: vpc-resource-controller
      containers:
      - command:
        - /vpc-resource-controller
        args:
        - -stderrthreshold=info
        image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/vpc-resource-controller:0.2.3
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            host: 127.0.0.1
            path: /healthz
            port: 61779
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        name: vpc-resource-controller
        securityContext:
          privileged: true
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/os: linux
        beta.kubernetes.io/arch: amd64
---
```
```
❯ kube2pulumi csharp -f .\vpc-resource-controller.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x48 pc=0xf382ed]

goroutine 1 [running]:
github.com/goccy/go-yaml/ast.(*filterWalker).Visit(0xc0005cf460, 0x0, 0x0, 0xc0005cf240, 0x56)
        /home/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.8.0/ast/ast.go:1472 +0x2d
github.com/goccy/go-yaml/ast.Walk(0x146fb00, 0xc0005cf460, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.8.0/ast/ast.go:1428 +0x53
github.com/goccy/go-yaml/ast.Filter(...)
        /home/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.8.0/ast/ast.go:1481
github.com/pulumi/kube2pulumi/pkg/yaml2pcl.convert(0xc0000344a0, 0x1e, 0xc00058bcc0, 0x5, 0x8, 0x0, 0xc00051bb70, 0x497c78, 0x1072ce0, 0xc0000ca700, ...)
        /home/runner/work/kube2pulumi/kube2pulumi/pkg/yaml2pcl/yaml2pcl.go:83 +0x13a
github.com/pulumi/kube2pulumi/pkg/yaml2pcl.ConvertFile(0xc0000344a0, 0x1e, 0xc0000ca700, 0x98, 0x14abcc0, 0x14abcc0, 0xc9b4e2, 0x1072ce0, 0xc0000ca700)
        /home/runner/work/kube2pulumi/kube2pulumi/pkg/yaml2pcl/yaml2pcl.go:33 +0x16f
github.com/pulumi/kube2pulumi/pkg/kube2pulumi.Kube2PulumiFile(0xc0000344a0, 0x1e, 0x124106d, 0x6, 0x1072ce0, 0xc0000ca700, 0x1d56020, 0x0, 0x4, 0x0, ...)
        /home/runner/work/kube2pulumi/kube2pulumi/pkg/kube2pulumi/kube2pulumi.go:14 +0x46
github.com/pulumi/kube2pulumi/cmd/kube2pulumi/util.RunConversion(0x0, 0x0, 0xc0000344a0, 0x1e, 0x124106d, 0x6, 0x4, 0x123e4ef, 0x4, 0xcc9740)
        /home/runner/work/kube2pulumi/kube2pulumi/cmd/kube2pulumi/util/conversion.go:26 +0xa7
github.com/pulumi/kube2pulumi/cmd/kube2pulumi/csharp.Command.func1(0xc00044cdc0, 0xc00058c880, 0x0, 0x2, 0x0, 0x0)
        /home/runner/work/kube2pulumi/kube2pulumi/cmd/kube2pulumi/csharp/cli.go:18 +0xc8
github.com/spf13/cobra.(*Command).execute(0xc00044cdc0, 0xc00058c840, 0x2, 0x2, 0xc00044cdc0, 0xc00058c840)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x45a
github.com/spf13/cobra.(*Command).ExecuteC(0xc00044c000, 0x44570e, 0x1ca44e0, 0xc00006df78)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /home/runner/work/kube2pulumi/kube2pulumi/cmd/kube2pulumi/main.go:42 +0x32
```
After removing the trailing `---`, it works:
```
❯ kube2pulumi csharp -f .\vpc-resource-controller.yaml

Diagnostics:

Conversion successful! Generated File: Program.cs
```
