### ISSUE TITLE
Role template triggers Invalid Exception

### ISSUE THREAD

**Issue by XBeg9** [pulumi/kube2pulumi#56]
```yaml
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mm-database
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - patch
  - update
  # the following three privileges are necessary only when using endpoints
  - create
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create

```

Response:

```bash
kube2pulumi typescript -f yamls/templates/database/role.yaml                                                                                                                 Error: Error: Invalid expression

  on pcl-910958302.pp line 51:
  52: ]

Expected the start of an expression, but found an invalid expression token.
```
