### ISSUE TITLE
kube2pulumi binding types error

### ISSUE THREAD

**Issue by Walther** [pulumi/kube2pulumi#58]
Given `example.yaml`

```yaml
apiVersion: v1
kind: Pod
metadata:
  namespace: foo
  name: bar
spec:
  containers:
    - name: nginx
      image: nginx:1.14-alpine
      resources:
        limits:
          memory: 20Mi
          cpu: 0.2
```

Running `kube2pulumi typescript -f ./example.yaml` results in

```
2021/01/22 19:58:34 failed to bind program: 
Error: binding types: type kubernetes:core/v1:ServiceSpecType must be an object, not a string
Usage:
  kube2pulumi typescript [flags]

Flags:
  -h, --help   help for typescript

Global Flags:
  -d, --directory string   file path for directory to convert
  -f, --file string        YAML file to convert

unable to run program: binding types: type kubernetes:core/v1:ServiceSpecType must be an object, not a string
```

The same error can be reproduced with `go`, `python`, `csharp`, `all`.

Context:

```
brew info pulumi
pulumi: stable 2.18.1 (bottled), HEAD
Cloud native development platform
https://pulumi.io/
/usr/local/Cellar/pulumi/2.18.1 (18 files, 183.5MB) *
  Poured from bottle on 2021-01-22 at 19:05:25


brew info kube2pulumi
pulumi/tap/kube2pulumi: stable 0.0.5
Convert Kubernetes manifests to Pulumi code
https://pulumi.io
/usr/local/Cellar/kube2pulumi/0.0.5 (5 files, 27.4MB) *
  Built from source on 2021-01-22 at 19:30:36
```

OS: `macOS Big Sur 11.1 (20C69)`
