### ISSUE TITLE
[yaml2pcl] YAML lists generate invalid PCL

### ISSUE THREAD

**Issue by lblackstone** [pulumi/kube2pulumi#6]
The following YAML generates invalid PCL:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pulumi-kubernetes-operator
rules:
  - apiGroups:
      - foo
    resources:
      - pods
      - services
      - services/finalizers
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
```

```
resource pulumi-kubernetes-operator "kubernetes:rbac.authorization.k8s.io/v1:Role" {
	apiVersion = "rbac.authorization.k8s.io/v1"
	kind = "Role"
	metadata = {
		name = "pulumi-kubernetes-operator"
	}
	rules = [
		{
			apiGroups = [
				"foo"
			]
			resources = [
				"pods"
				"services"
				"services/finalizers"
				"endpoints"
				"persistentvolumeclaims"
				"events"
				"configmaps"
				"secrets"
			]
			verbs = [
				"create"
				"delete"
				"get"
				"list"
				"patch"
				"update"
				"watch"
			]
		}
	]
}

```

The items in the array need to be string separated like this:
```
resources = [
	"pods",
	"services",
	"services/finalizers",
	"endpoints",
	"persistentvolumeclaims",
	"events",
	"configmaps",
	"secrets"
]
```
