### ISSUE TITLE
Invalid C#-property ContainerPort generated for containerPorts

### ISSUE THREAD

**Issue by vipentti** [pulumi/kube2pulumi#60]
Hey!

Ran in to the following problem when using kube2pulumi with a file containing containerPort definitions.
kube2pulumi generates non-valid property named `ContainerPort` in C# for `containerPort` definition.
The property `ContainerPort` does not exist in the [ContainerPortArgs](https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/dotnet/Core/V1/Inputs/ContainerPortArgs.cs#L22), the actual property in C# is named `ContainerPortValue`.

Problem can be reproduced with:

```yaml
# container-port-error.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: nginx-ingress-serviceaccount
      containers:
        - name: nginx-ingress-controller
          image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.20.0
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
```

Running

```sh
$ kube2pulumi csharp -f container-port-error.yaml
```

Generates the following code

```csharp
using Pulumi;
using Kubernetes = Pulumi.Kubernetes;

class MyStack : Stack
{
    public MyStack()
    {
        var nginx_ingress_controllerDeployment = new Kubernetes.Apps.V1.Deployment("nginx_ingress_controllerDeployment", new Kubernetes.Types.Inputs.Apps.V1.DeploymentArgs
        {
            ApiVersion = "apps/v1",
            Kind = "Deployment",
            Metadata = new Kubernetes.Types.Inputs.Meta.V1.ObjectMetaArgs
            {
                Name = "nginx-ingress-controller",
            },
            Spec = new Kubernetes.Types.Inputs.Apps.V1.DeploymentSpecArgs
            {
                Replicas = 1,
                Template = new Kubernetes.Types.Inputs.Core.V1.PodTemplateSpecArgs
                {
                    Spec = new Kubernetes.Types.Inputs.Core.V1.PodSpecArgs
                    {
                        ServiceAccountName = "nginx-ingress-serviceaccount",
                        Containers =
                        {
                            new Kubernetes.Types.Inputs.Core.V1.ContainerArgs
                            {
                                Name = "nginx-ingress-controller",
                                Image = "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.20.0",
                                Ports =
                                {
                                    new Kubernetes.Types.Inputs.Core.V1.ContainerPortArgs
                                    {
                                        Name = "http",
                                        // Does not exist in ContainerPortArgs, the property is named ContainerPortValue
                                        ContainerPort = 80,
                                    },
                                    new Kubernetes.Types.Inputs.Core.V1.ContainerPortArgs
                                    {
                                        Name = "https",
                                        // Does not exist in ContainerPortArgs, the property is named ContainerPortValue
                                        ContainerPort = 443,
                                    },
                                },
                            },
                        },
                    },
                },
            },
        });
    }
}
```

Version of kube2pulumi in use:

```sh
$ kube2pulumi.exe version
v0.0.8
```

The csproj contains the following version of Pulumi.Kubernetes:
```
<PackageReference Include="Pulumi.Kubernetes" Version="2.8.0" />
```
