### ISSUE TITLE
Cannot convert PodSecurityPolicy yaml to typescript

### ISSUE THREAD

**Issue by suraciii** [pulumi/kube2pulumi#66]
When `kube2pulumi.exe typescript -f psp.yaml`, it shows: 
```
unable to run program: Error: Argument or block definition required
  on C:\Users\***\AppData\Local\Temp\pcl-532074835.pp line 0:
   1: resource 00_rook_privilegedPodSecurityPolicy "kubernetes:policy/v1beta1:PodSecurityPolicy" {
An argument or block definition is required here. To set an argument, use the equals sign "=" to introduce the argument value.
```

the yaml file:
``` yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: 00-rook-privileged
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: "runtime/default"
    seccomp.security.alpha.kubernetes.io/defaultProfileName: "runtime/default"
spec:
  privileged: true
  allowedCapabilities:
    - SYS_ADMIN
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  volumes:
    - configMap
    - downwardAPI
    - emptyDir
    - persistentVolumeClaim
    - secret
    - projected
    - hostPath
    - flexVolume
  hostIPC: true
  hostPID: true
  hostNetwork: true
  hostPorts:
    - min: 6789
      max: 6790
    - min: 3300
      max: 3300
    - min: 6800
      max: 7300
    - min: 8443
      max: 8443
    - min: 9283
      max: 9283
```
