### ISSUE TITLE
Quoted "ApiVersion" property string causes error

### ISSUE THREAD

**Issue by cstclair-tunein** [pulumi/kube2pulumi#76]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When one attempts to convert a YAML file that includes a quoted string for the "APIVersion" key, an error is thrown of the form:

```
❯ kube2pulumi go

Diagnostics:
<nil>: malformed yaml: apiVersion not specified; apiVersion field for the resource is not specified and is required

Conversion successful! Generated File: /Users/[redacted]/tmp/kube2pulumi/main.go
```

The yaml file is of the form:

```
# depl.yaml
apiVersion: "apps/v1" # here is the issue
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
 ```

### Steps to reproduce

1. Copy the `depl.yaml` file into a directory
2. run `kube2pulumi go`

Expected: Pulumi code is generated from the manifest
Actual: An error is thrown ( see above )
