### ISSUE TITLE
Commented entries in "env" object that are sandwiched between other entries cause failure

### ISSUE THREAD

**Issue by GavinRay97** [pulumi/kube2pulumi#78]
If you delete the entry before or after the commented one in `env`, it works, but otherwise it fails with:

```sh
unable to run program: Error: Invalid expression

  on pcl-158852422.pp line 1543:
1544: ]
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth
    namespace: default
    labels:
        app: auth
spec:
    selector:
        matchLabels:
            app: auth
    strategy:
        rollingUpdate:
            maxUnavailable: 0
    replicas: 1
    template:
        metadata:
            annotations:
            labels:
                app: auth
        spec:
            serviceAccountName: auth
            initContainers:
            containers:
                - name: auth
                  image: foo
                  env:
                      - name: SESSION_KEY
                        valueFrom:
                            secretKeyRef:
                                key: SESSION_KEY
                                name: secrets
                      #- name: SESSION_COOKIE_SECURE
                      #  value: "true"
                      - name: GITHUB_CLIENT_ID
                        valueFrom:
                            secretKeyRef:
                                key: GITHUB_CLIENT_ID
                                name: secrets
                  resources:
                      requests:
                          cpu: 50m
                          memory: 64Mi
                      limits:
                          cpu: 200m
                          memory: 128Mi
```
